version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    commit-message:
      prefix: npm
    ignore:
      - dependency-name: "@types/node"
        versions: ">=15.x"
